/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SOURCES.UI;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;

/**
 *
 * @author user
 */
public class CelluleCombo extends javax.swing.JPanel {
    
    private ImageIcon iconeEdition;
    public static int ALIGNE_GAUCHE = 0;
    public static int ALIGNE_CENTRE = 1;
    public static int ALIGNE_DROITE = 2;
    /**
     * Creates new form PanValeurTable
     */
    public CelluleCombo(String val, int alignement, ImageIcon iconeEdition) {
        initComponents();
        this.iconeEdition = iconeEdition;
        setValeur(val);
        if(alignement == ALIGNE_DROITE){
            labvaleur.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        }else if(alignement == ALIGNE_CENTRE){
            labvaleur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        }else{
            labvaleur.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        }
        labvaleur.setIcon(this.iconeEdition);
    }
    
    
    
    
    private void ecouterLigneImpare(int row){
        if((row % 2) == 0){
            this.setBackground(Color.WHITE);
        }else{
            this.setBackground(Color.lightGray);
        }
    }
    
    public void ecouterSelection(boolean isSelected, int row){
        if(isSelected == true){
            labvaleur.setFont(new java.awt.Font("Tahoma", Font.BOLD, 11));
            labvaleur.setForeground(Color.WHITE);
            this.setBackground(Color.BLACK);
        }else{
            labvaleur.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 11));
            labvaleur.setForeground(Color.BLACK);
            ecouterLigneImpare(row);
        }
    }
    
    
    public void setValeur(String val){
        this.labvaleur.setText(val);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labvaleur = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(160, 24));

        labvaleur.setBackground(new java.awt.Color(255, 255, 255));
        labvaleur.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labvaleur.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labvaleur.setText("2000.15 $");
        labvaleur.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labvaleur, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labvaleur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labvaleur;
    // End of variables declaration//GEN-END:variables
}
